# Generated by Django 3.0.6 on 2021-01-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Milk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Farm_Data',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
