# Generated by Django 3.0.6 on 2021-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_deliveryboy_deliveryboy_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
