# Generated by Django 3.0.7 on 2021-01-22 11:51

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200104_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=products.models.upload_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='product_alias',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='products_type',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weightage_size',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Milk', 'milk'), ('Curd', 'curd'), ('Ghee', 'ghee'), ('Panner', 'panner'), ('Butter', 'butter')], max_length=120),
        ),
    ]
