# Generated by Django 3.0.7 on 2021-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210122_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
        ),
    ]
