# Generated by Django 3.0.7 on 2021-01-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_newarrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(max_length=50)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('Driver_License', models.CharField(max_length=50)),
                ('Driver_Address', models.TextField(max_length=300)),
                ('Driver_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('Employee_Address', models.TextField(max_length=300)),
                ('Employee_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow', models.CharField(max_length=50)),
                ('buffello', models.CharField(max_length=50)),
                ('cow_milk', models.IntegerField()),
                ('buffello_milk', models.IntegerField()),
                ('Dhana', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Name', models.CharField(max_length=50)),
                ('Vehicle_Number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flashoffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
