# Generated by Django 3.0.6 on 2021-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pro_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
