# Generated by Django 3.0.6 on 2021-01-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_pro_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pro_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
